// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

public interface CalcularMulta {

	public double calcularTaxa(int dias);
};
