// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

public class Estudante implements Utilizadores {

	private String Nome;
	private String NumeroCartao;
	private String Curso;
	private int NumeroEmprestimos;
	private int PrazoEntrega;
	private double Coima;
	private boolean Newsletter;

	
	public Estudante(String nome, String numeroCartao, String curso) {
		Nome = nome;
		Curso = curso;
		NumeroEmprestimos = 0;
		Coima = 0;
		PrazoEntrega = 0;
		Newsletter = false;
		NumeroCartao = numeroCartao;
	}

	public String getCurso() {
		return Curso;
	}

	public int getNumeroEmprestimos() {
		return NumeroEmprestimos;
	}

	public void setNumeroEmprestimos(int numeroEmprestimos) {
		NumeroEmprestimos = numeroEmprestimos;
	}

	public double getCoima() {
		return Coima;
	}

	public void setCoima(double coima) {
		Coima = coima;
	}

	public int getPrazoEntrega() {
		return PrazoEntrega;
	}

	public void setPrazoEntrega(int prazoEntrega) {
		PrazoEntrega = prazoEntrega;
	}

	public String getNome() {
		return Nome;
	}

	public boolean isNewsletter() {
		return Newsletter;
	}

	public void setNewsletter(boolean newsletter) {
		Newsletter = newsletter;
	}

	public String getNumeroCartao() {
		return NumeroCartao;
	}

	@Override
	public String toString() {
		return "Estudante [Nome=" + Nome + ", NumeroCartao=" + NumeroCartao + ", Curso=" + Curso
				+ ", NumeroEmprestimos=" + NumeroEmprestimos + ", PrazoEntrega=" + PrazoEntrega + ", Coima=" + Coima
				+ ", Newsletter=" + Newsletter + "]";
	}
	
};
