// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import java.util.ArrayList;

public class Estudante implements Utilizadores {

	//variáveis
	private String Nome;
	private String NumeroCartao;
	private String Curso;
	private int NumeroEmprestimos;
	private int PrazoEntrega;
	private double Coima;
	private boolean Newsletter;
	public ArrayList<Emprestimo> emprestimos;
	
	//construtor
	public Estudante(String nome, String numeroCartao, String curso) {
		Nome = nome;
		Curso = curso;
		NumeroEmprestimos = 0;
		Coima = 0;
		PrazoEntrega = 0;
		Newsletter = false;
		NumeroCartao = numeroCartao;
		emprestimos = new ArrayList<Emprestimo>();
	}
	
	
	public void inserirEmprestimo(Emprestimo e) {//insere Emprestimo
    	emprestimos.add(e);
    }// fim do método inserirEmprestimo
	
	public void imprimirEmprestimos() {//imprimir Emprestimos
		for (Emprestimo e: emprestimos) {
			System.out.println(e.toString());
		}
	}// fim do método imprimirEmprestimos
	
	public Emprestimo pesquisarEmprestimo(String p) {// pesquisa emprestimos
		for (Emprestimo emp : emprestimos) {
            if (emp.getP().getTitulo().equals(p)) {
                return emp;
            }
        }
        return null;
	}// fim do método pesquisarEmprestimo
	
	//getters e setters
	public String getCurso() {
		return Curso;
	}

	public int getNumeroEmprestimos() {
		return NumeroEmprestimos;
	}

	public void setNumeroEmprestimos(int numeroEmprestimos) {
		NumeroEmprestimos = numeroEmprestimos;
	}

	public double getCoima() {
		return Coima;
	}

	public void setCoima(double coima) {
		Coima = coima;
	}

	public int getPrazoEntrega() {
		return PrazoEntrega;
	}

	public void setPrazoEntrega(int prazoEntrega) {
		PrazoEntrega = prazoEntrega;
	}

	public String getNome() {
		return Nome;
	}

	public boolean isNewsletter() {
		return Newsletter;
	}

	public void setNewsletter(boolean newsletter) {
		Newsletter = newsletter;
	}

	public String getNumeroCartao() {
		return NumeroCartao;
	}

	//to String
	@Override
	public String toString() {
		return "Estudante [Nome=" + Nome + ", NumeroCartao=" + NumeroCartao + ", Curso=" + Curso
				+ ", NumeroEmprestimos=" + NumeroEmprestimos + ", PrazoEntrega=" + PrazoEntrega + ", Coima=" + Coima
				+ ", Newsletter=" + Newsletter + "]";
	}
	
}//fim da classe
