// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

/************************************************************/
/**
 * 
 */
public class Externo implements Utilizadores{
	
	private String Nome;
	private String NumeroCartao;
	private double Coima;
	private boolean Newsletter;
	
	public Externo(String nome, String numeroCartao) {
		Coima = 0;
		Nome = nome;
		Newsletter = false;
		NumeroCartao = numeroCartao;
	}

	public double getCoima() {
		return Coima;
	}

	public void setCoima(double coima) {
		Coima = coima;
	}

	public boolean isNewsletter() {
		return Newsletter;
	}

	public void setNewsletter(boolean newsletter) {
		Newsletter = newsletter;
	}

	public String getNome() {
		return Nome;
	}

	public String getNumeroCartao() {
		return NumeroCartao;
	}

	@Override
	public String toString() {
		return "Externo [Nome=" + Nome + ", NumeroCartao=" + NumeroCartao + ", Coima=" + Coima + ", Newsletter="
				+ Newsletter + "]";
	}

};
