// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import java.util.ArrayList;
import java.util.StringTokenizer;
import Model.Livro;


public class GerirBiblioteca {

	private ArrayList<Utilizadores> utilizadores;
	private ArrayList<Publicacao> publicacoes;


    public GerirBiblioteca()
    {
    	utilizadores = new ArrayList<>();
    	publicacoes = new ArrayList<>();
    }

    public void adicionarUtilizador(String userInput)
    {
        UtilizadorFactoryInterface utilizadorFactory = new UtilizadorFactory();   
        utilizadores.add(utilizadorFactory.getProxUtil(userInput));
    }
    
    public void adicionarPublicacao(String userInput)
    {
        PublicacaoFactoryInterface publicacaoFactory = new PublicacaoFactory();     
        publicacoes.add(publicacaoFactory.getProxPub(userInput));
    }
    
    
    public void imprimirUtilizadores() {
    	if (utilizadores.isEmpty())
    	{
    		System.out.println("Não existem utilizadores.");
    	}
    	else {
    	for(Utilizadores u : utilizadores)
    	{
    		System.out.println(u.toString());
    	}
    	}
    }
    
    public Utilizadores pesquisarUtilizadores(String num) {
    	for (Utilizadores u : utilizadores) {
			if (num.equals(u.getNumeroCartao())) {
				return u;
			}
		}
		return null;
    }
    
    public void imprimirPublicacoes() {
    	if (publicacoes.isEmpty())
    	{
    		System.out.println("Não existem publicacoes.");
    	}
    	else {
    	for(Publicacao p : publicacoes)
    	{
    		System.out.println(p.toString());
    	}
    	}
    }
    
    public Publicacao pesquisarPublicacoes(String titulo) {
    	StringTokenizer tokenizer;
        tokenizer = new StringTokenizer(titulo, ",");
    	for (Publicacao p : publicacoes) {
			if (tokenizer.equals(p)) {
				return p;
			}
		}
		return null;
    }
    
    public void emprestarLivro(String u, String l) {
    	Publicacao p = pesquisarPublicacoes(l);
    	if(p instanceof Livro) {
    		Utilizadores util = pesquisarUtilizadores(u);
    	}
    		
    }

};
