// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import java.util.ArrayList;
import Model.Livro;


public class GerirBiblioteca {

	private ArrayList<Utilizadores> utilizadores;
	private ArrayList<Publicacao> publicacoes;
	
    public GerirBiblioteca()
    {
    	utilizadores = new ArrayList<>();
    	publicacoes = new ArrayList<>();
    }

    public void adicionarUtilizador(String userInput)
    {
        UtilizadorFactoryInterface utilizadorFactory = new UtilizadorFactory();   
        utilizadores.add(utilizadorFactory.getProxUtil(userInput));
    }
    
    public void adicionarPublicacao(String userInput)
    {
        PublicacaoFactoryInterface publicacaoFactory = new PublicacaoFactory();     
        publicacoes.add(publicacaoFactory.getProxPub(userInput));
    }
    
    
    public void imprimirUtilizadores() {
    	if (utilizadores.isEmpty())
    	{
    		System.out.println("Não existem utilizadores.");
    	}
    	else {
    	for(Utilizadores u : utilizadores)
    	{
    		System.out.println(u.toString());
    	}
    	}
    }
    
    public boolean pesquisarUtilizadores(String num) {
    	for (Utilizadores u : utilizadores) {
			if (num.equals(u.getNumeroCartao())) {
				return true;
			}
		}
		return false;
    }
    
    public Utilizadores pesquisarUtilizadores2(String num) {
    	for (Utilizadores u : utilizadores) {
			if (num.equals(u.getNumeroCartao())) {
				return u;
			}
		}
		return null;
    }
    
    public void imprimirPublicacoes() {
    	if (publicacoes.isEmpty())
    	{
    		System.out.println("Não existem publicacoes.");
    	}
    	else {
    	for(Publicacao p : publicacoes)
    	{
    		System.out.println(p.toString());
    	}
    	}
    }
    
    public boolean pesquisarPublicacoes(String titulo) {
    	for (Publicacao p : publicacoes) {
			if (titulo.equals(p.getTitulo())) {
				return true;
			}
		}
		return false;
    }
    
    public Publicacao pesquisarPublicacoes2(String titulo) {
    	for (Publicacao p : publicacoes) {
			if (titulo.equals(p.getTitulo())) {
				return p;
			}
		}
		return null;
    }
    
    public void inserirLivroUtilizador(String u, String l) {
    	Publicacao p = pesquisarPublicacoes2(l);
    	Utilizadores util = pesquisarUtilizadores2(u);
    	if (p instanceof Livro) {
    		Emprestimo emp = new Emprestimo(util, p);
            util.inserirEmprestimo(emp);
    	}
    }
    
    public boolean pesquisarLivrosEmprestados(String l, String u) {
    
    	Utilizadores util = pesquisarUtilizadores2(u);
    	if (util!=null) 
    		{Emprestimo emp=util.pesquisarEmprestimo(l);
    		if (emp!=null)
			return true;	
    		else return false;
			
    		}
    	return false;
    }
}
