// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

public class Livro implements Publicacao {

	private String Titulo;
	private String Autor;
	private String Editor;
	private String Tipo;
	private String ISBN;
	private boolean Emprestado;
	
	
	public Livro(String titulo, String autor, String editor, String tipo, String iSBN) {
		Titulo = titulo;
		Editor = editor;
		Autor = autor;
		ISBN = iSBN;
		Emprestado = false;
		Tipo = tipo;
	}

	public String getTitulo() {
		return Titulo;
	}

	public String getEditor() {
		return Editor;
	}

	public String getAutor() {
		return Autor;
	}

	public String getISBN() {
		return ISBN;
	}


	public boolean isEmprestado() {
		return Emprestado;
	}

	public void setEmprestado(boolean emprestado) {
		Emprestado = emprestado;
	}

	public String getTipo() {
		return Tipo;
	}


	@Override
	public String toString() {
		return "Livro [Titulo=" + Titulo + ", Autor=" + Autor + ", Editor=" + Editor + ", Tipo=" + Tipo + ", ISBN="
				+ ISBN + ", Emprestado=" + Emprestado + "]";
	}
	
};
