// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import java.util.Scanner;

public class Main {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		GerirBiblioteca lista = new GerirBiblioteca();
		
		System.out.println("-------------------------->Menu<--------------------------");
		System.out.println("0 - Sair");
		System.out.println("1 - Registar um Utilizador");
		System.out.println("2 - Imprimir Utilizadores");
		System.out.println("3 - Registar uma Publicacao");
		System.out.println("4 - Imprimir Publicacoes");
		System.out.println("5 - Requisitar Emprestimo");
		System.out.println("-------------------------->Menu<--------------------------");
		String input = ("Escolha uma das opções: ");
		int op = sc.nextInt();
		while(op < 0 || op > 5 ) {
			input = ("Por Favor, Insira Valores entre 1 a 5!\nEscolha uma das opções: ");
			op = sc.nextInt();
		}	
		while (op != 0) {
			switch (op) {
			case 1: // Registar um Utilizador
			{
				System.out.println("Qual o tipo de Utilizador? E-Estudante, S-Staff, EXT-Exterior");
				String r = sc.next();
				lista.adicionarUtilizador(r);
			}
				break;
			case 2: // Imprimir Utilizadores
			{
				lista.imprimirUtilizadores();
			}
				break;
			case 3: // Registar uma Publicacão
			{
				System.out.println("Qual o tipo de Publicacao? L-Livro, PP-PublicacaoPeriodica, OR-ObraReferencia");
				String r = sc.next();
				lista.adicionarPublicacao(r);
			}
				break;
			case 4: // Imprimir Utilizadores
			{
				lista.imprimirPublicacoes();
			}
				break;
			case 5: // Requisitar Emprestimo
			{
				System.out.println("Numero do cartao do Utilizador?");
				String r = sc.next();
				
				System.out.println("Nome do Livro?");
				String r2 = sc.next();
				lista.inserirLivroUtilizador(r, r2);			
			}
				break;
				default: System.out.println("Erro");
			}
			System.out.println("-------------------------->Menu<--------------------------");
			System.out.println("0 - Sair");
			System.out.println("1 - Registar um Utilizador");
			System.out.println("2 - Imprimir Utilizadores");
			System.out.println("3 - Registar uma Publicacao");
			System.out.println("4 - Imprimir Publicacoes");
			System.out.println("5 - Requisitar Emprestimo");
			System.out.println("-------------------------->Menu<--------------------------");
			input = ("Escolha uma das opções: ");
			op = sc.nextInt();
			while(op < 0 || op > 5 ) {
				input = ("Por Favor, Insira Valores entre 1 a 5!\nEscolha uma das opções: ");
				op = sc.nextInt();
			}
			sc.close();
		}
	}
}
