// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

public class MultaEstudante implements CalcularMulta {
	
	@Override
	public double calcularTaxa(int dias) {
		return dias*0.50;	
		}
};
