// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

public class MultaExterna implements CalcularMulta {
	
	@Override
	public double calcularTaxa(int dias) {
		return dias*1;	
		}
};
