// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

public class ObraReferencia implements Publicacao {

	private String Titulo;
	private String Autor;
	private String Editor;
	private String Tipo;
	
	public ObraReferencia(String titulo, String autor, String editor, String tipo) {
		Editor = editor;
		Autor = autor;
		Titulo = titulo;
		Tipo = tipo;
	}

	public String getEditor() {
		return Editor;
	}

	public void setEditor(String editor) {
		Editor = editor;
	}

	public String getAutor() {
		return Autor;
	}

	public void setAutor(String autor) {
		Autor = autor;
	}

	public String getTitulo() {
		return Titulo;
	}

	public void setTitulo(String titulo) {
		Titulo = titulo;
	}

	public String getTipo() {
		return Tipo;
	}

	public void setTipo(String tipo) {
		Tipo = tipo;
	}

	@Override
	public String toString() {
		return "ObraReferencia [Titulo=" + Titulo + ", Autor=" + Autor + ", Editor=" + Editor + ", Tipo=" + Tipo + "]";
	}
	
};
