// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

public class OrdemAtraso {

	 private CalcularMulta strategy;
	
	public void context(CalcularMulta strategy) {
		this.strategy = strategy;
	}
	
	public double executarStrategy(int dias){
	      return strategy.calcularTaxa(dias);
	   }
	
};
