// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

public interface Publicacao {

	String getTitulo();
	String getAutor();
	String getEditor();
	String getTipo();

};
