// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

/************************************************************/
/**
 * 
 */
public interface PublicacaoFactoryInterface {
	Publicacao getProxPub(String orderLine);
};
