// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;
public class Staff implements Utilizadores{
	
	private String Nome;
	private String NumeroCartao;
	private int Tipo;
	private int NumeroEmprestimos;
	private int PrazoEntrega;
	private boolean Newsletter;
	
	public Staff(String nome, String numeroCartao, int tipo) {
		PrazoEntrega = 0;
		Nome = nome;
		Newsletter = false;
		NumeroCartao = numeroCartao;
		Tipo = tipo;
	}

	public int getPrazoEntrega() {
		return PrazoEntrega;
	}

	public void setPrazoEntrega(int prazoEntrega) {
		PrazoEntrega = prazoEntrega;
	}

	public boolean isNewsletter() {
		return Newsletter;
	}

	public void setNewsletter(boolean newsletter) {
		Newsletter = newsletter;
	}

	public int getNumeroEmprestimos() {
		return NumeroEmprestimos;
	}

	public void setNumeroEmprestimos(int numeroEmprestimos) {
		NumeroEmprestimos = numeroEmprestimos;
	}

	public String getNome() {
		return Nome;
	}

	public String getNumeroCartao() {
		return NumeroCartao;
	}

	public int getTipo() {
		return Tipo;
	}

	@Override
	public String toString() {
		return "Staff [Nome=" + Nome + ", NumeroCartao=" + NumeroCartao + ", Tipo=" + Tipo + ", NumeroEmprestimos="
				+ NumeroEmprestimos + ", PrazoEntrega=" + PrazoEntrega + ", Newsletter=" + Newsletter + "]";
	}

};
