// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

public interface Utilizadores {

	 String getNumeroCartao();
	 String getNome();
	 boolean isNewsletter();

};

