// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import java.util.NoSuchElementException;
import java.util.StringTokenizer;

public class UtilizadorFactory implements UtilizadorFactoryInterface{

	private static final String ESTUDANTE = "E";
	private static final String STAFF = "S";
	private static final String EXTERNO = "EXT";
	
	public UtilizadorFactory() {
		
	}

	private Utilizadores registarEstudante(StringTokenizer tok)throws NoSuchElementException {//Este método cria as string que vão para o construtor da 
																							  //Estudante com tokenizer
		
		 String Nome = tok.nextToken();
		 String NumeroCartao = tok.nextToken();
		 String Curso = tok.nextToken();
		 return new Estudante(Nome, NumeroCartao, Curso);
	}


	private Utilizadores registarStaff(StringTokenizer tok)throws NoSuchElementException {//Este método cria as string que vão para o construtor da 
																						  //Staff com tokenizer		
		 String Nome = tok.nextToken();	
		 String NumeroCartao = tok.nextToken();
		 String TString = tok.nextToken();
		 int Tipo = Integer.valueOf(TString).intValue();
		 return new Staff(Nome, NumeroCartao, Tipo);
	}

	
	private Utilizadores registarExterno(StringTokenizer tok)throws NoSuchElementException {//Este método cria as string que vão para o construtor da 
		  																					//Externo com tokenizer
		String Nome = tok.nextToken();
		String NumeroCartao = tok.nextToken();
		
		return new Externo (Nome, NumeroCartao);
	}


	public Utilizadores getProxUtil(String orderLine) {
		
		StringTokenizer tokenizer;
        tokenizer = new StringTokenizer(orderLine, ",");
        
        try
        {
            // Construct an instance of a class which implements Utilizador
            String orderLineType = tokenizer.nextToken();
            if (orderLineType.equals(ESTUDANTE))
            {
                return registarEstudante(tokenizer);
            }
            else if (orderLineType.equals(STAFF))
            {
                return registarStaff(tokenizer);
            }
             else if (orderLineType.equals(EXTERNO))
            {
                return registarExterno(tokenizer);
            }
            else
            {
                System.out.println("Unknown item type");
                return null;
            }
        }
        catch (Exception e)
        {
            System.out.println("an error occurred: " + e.toString());
            return null;
        }
		
	}
}//fim da classe
