// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

public interface UtilizadorFactoryInterface {
	
	Utilizadores getProxUtil(String orderLine);
};
